### ISSUE TITLE
Access to ALL contacts

### ISSUE THREAD

**Issue by corsacca** [cairocoder01/disciple-tools-team-module#3]
https://github.com/cairocoder01/disciple-tools-team-module/blob/fc6dc7102fd774d959bf302cfdeea936c877f1be/post-type/module-base.php#L112

Discussion point.
This gives access to all contacts in the system, whether or not the contact is assigned to a team.
Would it be better to restrict to to "any contact assigned to a team"?

Only showing on :Team Collaborator.

**Comment by corsacca** [comment]
See https://github.com/cairocoder01/disciple-tools-team-module/pull/5

**Comment by cairocoder01** [comment]
#5 changes this to any access contact and I think that's sufficient. I'm happy to revisit this if there's a use case that pops up where the current functionality causes issues.
